/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/layout/AdminHeader.vue')['default']
    AdminHome: typeof import('./src/components/home/AdminHome.vue')['default']
    AdminMenu: typeof import('./src/components/layout/AdminMenu.vue')['default']
    AdminOverview: typeof import('./src/components/home/adminHome/AdminOverview.vue')['default']
    BarChart: typeof import('./src/components/home/adminHome/BarChart.vue')['default']
    BarChart2: typeof import('./src/components/trendcharts/saixuan/BarChart2.vue')['default']
    ChartsHome: typeof import('./src/components/trendcharts/ChartsHome.vue')['default']
    copy: typeof import('./src/components/trendcharts/saixuan/BarChart copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GoodsManagement: typeof import('./src/components/goods/GoodsManagement.vue')['default']
    KpiChart: typeof import('./src/components/trendcharts/charts/KpiChart.vue')['default']
    LineChart: typeof import('./src/components/home/adminHome/LineChart.vue')['default']
    MeiGui: typeof import('./src/components/trendcharts/charts/MeiGui.vue')['default']
    PieChart: typeof import('./src/components/home/adminHome/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaixuanHome: typeof import('./src/components/trendcharts/SaixuanHome.vue')['default']
    UserManagement: typeof import('./src/components/users/UserManagement.vue')['default']
    WeiXiu: typeof import('./src/components/home/adminHome/WeiXiu.vue')['default']
  }
}
